// Mapping of each Juz (1–30) to the surah names it contains.
// Surah names match QURAN_ORDER exactly (used for filtering in onboarding).
// A surah that spans two Juz appears in both.

export const JUZ_SURAHS = {
  1:  ['Al-Fatiha', 'Al-Baqara'],
  2:  ['Al-Baqara', 'Al-Imran'],
  3:  ['Al-Imran', 'An-Nisa'],
  4:  ['An-Nisa', 'Al-Maida'],
  5:  ['Al-Maida', 'Al-Anam'],
  6:  ['Al-Anam', 'Al-Araf'],
  7:  ['Al-Araf', 'Al-Anfal', 'At-Tawba'],
  8:  ['Al-Anfal', 'At-Tawba'],
  9:  ['At-Tawba', 'Yunus', 'Hud', 'Yusuf'],
  10: ['Yunus', 'Hud', 'Yusuf'],
  11: ['Yusuf', 'Ar-Rad', 'Ibrahim', 'Al-Hijr', 'An-Nahl'],
  12: ['Hud', 'Yusuf', 'Ar-Rad', 'Ibrahim', 'Al-Hijr', 'An-Nahl', 'Al-Isra'],
  13: ['Yusuf', 'Ar-Rad', 'Ibrahim', 'Al-Hijr', 'An-Nahl', 'Al-Isra', 'Al-Kahf'],
  14: ['Al-Hijr', 'An-Nahl', 'Al-Isra', 'Al-Kahf', 'Maryam', 'Ta-Ha'],
  15: ['Al-Isra', 'Al-Kahf', 'Maryam', 'Ta-Ha', 'Al-Anbiya'],
  16: ['Al-Kahf', 'Maryam', 'Ta-Ha', 'Al-Anbiya', 'Al-Hajj'],
  17: ['Al-Anbiya', 'Al-Hajj', 'Al-Muminun', 'An-Nur', 'Al-Furqan'],
  18: ['Al-Muminun', 'An-Nur', 'Al-Furqan', 'Ash-Shuara', 'An-Naml'],
  19: ['Al-Furqan', 'Ash-Shuara', 'An-Naml', 'Al-Qasas', 'Al-Ankabut'],
  20: ['An-Naml', 'Al-Qasas', 'Al-Ankabut', 'Ar-Rum', 'Luqman', 'As-Sajda'],
  21: ['Al-Ankabut', 'Ar-Rum', 'Luqman', 'As-Sajda', 'Al-Ahzab'],
  22: ['Al-Ahzab', 'Saba', 'Fatir', 'Ya-Sin'],
  23: ['Ya-Sin', 'As-Saffat', 'Sad', 'Az-Zumar'],
  24: ['Az-Zumar', 'Ghafir', 'Fussilat'],
  25: ['Fussilat', 'Ash-Shura', 'Az-Zukhruf', 'Ad-Dukhan', 'Al-Jathiya'],
  26: ['Al-Ahqaf', 'Muhammad', 'Al-Fath', 'Al-Hujurat', 'Qaf', 'Adh-Dhariyat'],
  27: ['Adh-Dhariyat', 'At-Tur', 'An-Najm', 'Al-Qamar', 'Ar-Rahman', 'Al-Waqia', 'Al-Hadid', 'Al-Mujadila', 'Al-Hashr', 'Al-Mumtahana', 'As-Saf', 'Al-Jumua', 'Al-Munafiqun', 'At-Taghabun', 'At-Talaq', 'At-Tahrim'],
  28: ['Al-Mujadila', 'Al-Hashr', 'Al-Mumtahana', 'As-Saf', 'Al-Jumua', 'Al-Munafiqun', 'At-Taghabun', 'At-Talaq', 'At-Tahrim', 'Al-Mulk', 'Al-Qalam', 'Al-Haqqa', 'Al-Maarij', 'Nuh', 'Al-Jinn', 'Al-Muzzammil', 'Al-Muddaththir', 'Al-Qiyama', 'Al-Insan', 'Al-Mursalat'],
  29: ['Al-Mursalat', 'An-Naba', 'An-Naziat', 'Abasa', 'At-Takwir', 'Al-Infitar', 'Al-Mutaffifin', 'Al-Inshiqaq', 'Al-Buruj', 'At-Tariq', 'Al-Ala', 'Al-Ghashiya', 'Al-Fajr', 'Al-Balad', 'Ash-Shams', 'Al-Layl', 'Ad-Duha', 'Ash-Sharh', 'At-Tin', 'Al-Alaq', 'Al-Qadr', 'Al-Bayyina', 'Az-Zalzala', 'Al-Adiyat', 'Al-Qaria', 'At-Takathur', 'Al-Asr', 'Al-Humaza', 'Al-Fil', 'Quraysh', 'Al-Maun', 'Al-Kawthar', 'Al-Kafirun', 'An-Nasr', 'Al-Masad', 'Al-Ikhlas', 'Al-Falaq', 'An-Nas'],
  30: ['An-Naba', 'An-Naziat', 'Abasa', 'At-Takwir', 'Al-Infitar', 'Al-Mutaffifin', 'Al-Inshiqaq', 'Al-Buruj', 'At-Tariq', 'Al-Ala', 'Al-Ghashiya', 'Al-Fajr', 'Al-Balad', 'Ash-Shams', 'Al-Layl', 'Ad-Duha', 'Ash-Sharh', 'At-Tin', 'Al-Alaq', 'Al-Qadr', 'Al-Bayyina', 'Az-Zalzala', 'Al-Adiyat', 'Al-Qaria', 'At-Takathur', 'Al-Asr', 'Al-Humaza', 'Al-Fil', 'Quraysh', 'Al-Maun', 'Al-Kawthar', 'Al-Kafirun', 'An-Nasr', 'Al-Masad', 'Al-Ikhlas', 'Al-Falaq', 'An-Nas'],
};
