/**
 * Manual tajweed segment overrides — generated by scripts/gen_overrides.mjs
 * Priority over quran_tajweed.json auto-generated data.
 * Rules: madd | ghunna | ikhfa | idgham | qalqala | null
 * Integrity: each entry's segments must reconstruct the exact original Arabic text.
 */
export const TAJWEED_OVERRIDES = {
  "108_1": [{"text":"إِ","rule":null},{"text":"نَّآ","rule":"ghunna"},{"text":" أَعۡطَيۡ","rule":null},{"text":"نَٰ","rule":"madd"},{"text":"كَ ٱلۡكَوۡثَرَ","rule":null}],
  "108_2": [{"text":"فَصَلِّ لِرَبِّكَ وَٱنۡحَرۡ","rule":null}],
  "108_3": [{"text":"إِ","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":" شَانِئَكَ هُوَ ٱلۡأَبۡتَرُ","rule":null}],
  "109_1": [{"text":"قُلۡ ","rule":null},{"text":"يَـٰٓ","rule":"madd"},{"text":"أَيُّهَا ٱلۡكَٰفِرُونَ","rule":null}],
  "109_2": [{"text":"لَآ","rule":"madd"},{"text":" أَعۡبُدُ مَا تَعۡبُدُو","rule":null},{"text":"نَ","rule":"ghunna"}],
  "109_3": [{"text":"وَ","rule":null},{"text":"لَآ","rule":"madd"},{"text":" أَنتُمۡ ","rule":null},{"text":"عَ","rule":"madd"},{"text":"ٰبِدُونَ م","rule":null},{"text":"َآ","rule":"madd"},{"text":" أَعۡبُدُ","rule":null}],
  "109_4": [{"text":"وَ","rule":null},{"text":"لَآ","rule":"madd"},{"text":" أَنَا۠ ","rule":null},{"text":"عَا","rule":"madd"},{"text":"بِدٞ مَّا عَبَدتُّمۡ","rule":null}],
  "109_5": [{"text":"وَ","rule":null},{"text":"لَآ","rule":"madd"},{"text":" أَنتُمۡ ","rule":null},{"text":"عَ","rule":"madd"},{"text":"ٰبِدُونَ م","rule":null},{"text":"َآ","rule":"madd"},{"text":" أَعۡبُدُ","rule":null}],
  "109_6": [{"text":"لَكُمۡ دِينُكُمۡ وَلِيَ دِينِ","rule":null}],
  "110_1": [{"text":"إِذَا ج","rule":null},{"text":"َآء","rule":"madd"},{"text":"َ نَصۡرُ ٱللَّهِ وَٱلۡفَتۡحُ","rule":null}],
  "110_2": [{"text":"وَرَأَيۡتَ ٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسَ يَدۡخُلُو","rule":null},{"text":"نَ","rule":"ghunna"},{"text":" فِي دِينِ ٱللَّهِ أَفۡوَاجٗا","rule":null}],
  "110_3": [{"text":"فَسَبِّحۡ بِحَمۡدِ رَبِّكَ وَٱسۡتَغۡفِرۡهُۚ إِ","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"هُۥ كَانَ تَوَّابَۢا","rule":null}],
  "111_1": [{"text":"تَبَّتۡ يَد","rule":null},{"text":"َآ","rule":"madd"},{"text":" أَبِي لَهَبٖ وَتَبَّ","rule":null}],
  "111_2": [{"text":"مَآ","rule":"madd"},{"text":" أَغۡنَىٰ عَنۡهُ مَالُهُۥ وَمَا كَسَبَ","rule":null}],
  "111_3": [{"text":"سَيَصۡل","rule":null},{"text":"َىٰ","rule":"madd"},{"text":" نَارٗا ذَاتَ لَهَبٖ","rule":null}],
  "111_4": [{"text":"وَٱمۡرَأَتُهُۥ حَ","rule":null},{"text":"مَّ","rule":"ghunna"},{"text":"الَةَ ٱلۡحَطَبِ","rule":null}],
  "111_5": [{"text":"فِي جِيدِهَا حَبۡلٞ ","rule":null},{"text":"مِّن","rule":"ghunna"},{"text":" مَّسَدِۭ","rule":null}],
  "112_1": [{"text":"قُلۡ هُوَ ٱللَّهُ أَحَدٌ","rule":null}],
  "112_3": [{"text":"لَمۡ يَلِدۡ وَلَمۡ ","rule":null},{"text":"يُو","rule":"madd"},{"text":"لَدۡ","rule":null}],
  "112_4": [{"text":"وَلَمۡ يَكُن لَّهُۥ كُفُوًا أَحَدُۢ","rule":null}],
  "113_1": [{"text":"قُلۡ أَعُوذُ بِرَبِّ ٱلۡفَلَقِ","rule":null}],
  "113_2": [{"text":"مِ","rule":null},{"text":"ن ش","rule":"ikhfa"},{"text":"َرِّ مَا خَلَقَ","rule":null}],
  "113_3": [{"text":"وَمِ","rule":null},{"text":"ن ش","rule":"ikhfa"},{"text":"َرِّ غَاسِقٍ إِذَا وَقَبَ","rule":null}],
  "113_4": [{"text":"وَمِ","rule":null},{"text":"ن ش","rule":"ikhfa"},{"text":"َرِّ ٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"فَّـٰثَٰتِ فِي ٱلۡعُقَدِ","rule":null}],
  "113_5": [{"text":"وَمِ","rule":null},{"text":"ن ش","rule":"ikhfa"},{"text":"َرِّ حَاسِدٍ إِذَا حَسَدَ","rule":null}],
  "114_1": [{"text":"قُلۡ أَعُوذُ بِرَبِّ ٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسِ","rule":null}],
  "114_2": [{"text":"مَلِكِ ٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسِ","rule":null}],
  "114_3": [{"text":"إِل","rule":null},{"text":"َٰ","rule":"madd"},{"text":"هِ ٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسِ","rule":null}],
  "114_4": [{"text":"مِ","rule":null},{"text":"ن ش","rule":"ikhfa"},{"text":"َرِّ ٱلۡوَسۡوَاسِ ٱلۡخَ","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسِ","rule":null}],
  "114_5": [{"text":"ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسِ","rule":null}],
  "114_6": [{"text":"مِنَ ٱلۡجِ","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"ةِ وَٱل","rule":null},{"text":"نَّ","rule":"ghunna"},{"text":"اسِ","rule":null}],
};
